### ISSUE TITLE
first hint is missing, code style

### ISSUE THREAD

**Issue by chinnonae** [guitarpawat/GuessingGame#1]
There should be a hint about the range of possible number. 
For example, `I'm thinking of a number between 1 and 20`

Also, you should leave a blank line between methods, and the import statement should be under package statement but over class
```
package ..;

import ..;
import ..;

/**
 * ...
 */
public class Example {
}
```

**Comment by guitarpawat** [comment]
I have change the format to
``` java
package ..;

import ..;
import ..;

/**
 * ...
 */
public class Example {
}
```
Add also add a hint and change some javadoc.
