### ISSUE TITLE
Logic error !

### ISSUE THREAD

**Issue by taveratch** [guitarpawat/GuessingGame#3]
getHint() did not do anything, it just return a string. Why you need to call it.

https://github.com/guitarpawat/GuessingGame/blob/master/src/lab01/Game.java#L41-L42

Btw, Game should not print anything to console. It should be a responsibility of GameConsole. Could you make it better ?

and line:41 and line:42 is kind of indentation error. if-else without bracket will performs only 1 statement under the condition statement.

**Comment by guitarpawat** [comment]
I have change `getHint()` to `println` by itself. Also, remove `else` on line:42 that can also runs game normally.
